In [1]:
from numpy import *
sqrt(2)

1.4142135623730951

In [2]:
15//6

2

In [3]:
abs(-3)

3

In [4]:
x1, y1, z1 = 23.7, -9.2, -7.8
print(y1)

-9.2


In [5]:
linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [6]:
arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
y = array([ 0. , 1.3,  5. , 10.9, 18.9, 28.7, 40. ])
t = array([ 0. , 0.49, 1. , 1.5 , 2.08, 2.55, 3.2 ])
# v_i = (y_i - y_i-1)/(t_i - t_i-1)
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])
v

array([  2.65306122,   7.25490196,  11.8       ,  13.79310345,
        20.85106383,  17.38461538])

In [9]:
c = arange(6)
print(c)
print('\n')
c = reshape(c, (2,3))
print(c)
print('\n')
print(c[0][2])
print('\n')
print(c[0,2])

[0 1 2 3 4 5]


[[0 1 2]
 [3 4 5]]


2


2


In [10]:
a = array([[1,2,3],[4,5,6]])
print(a)
b = array([[1,0],[0,-1],[-1,1]])
print('\n')
print(b)

[[1 2 3]
 [4 5 6]]


[[ 1  0]
 [ 0 -1]
 [-1  1]]


In [11]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
dot(a,b)

array([[-2,  1],
       [-2,  1]])

In [13]:
from numpy.random import *
rand()

0.8658152606161852

In [14]:
randn(10)

array([ 0.50288139, -0.87799887, -1.34786478,  0.84035071, -0.71167732,
       -0.39515077, -0.37903039, -0.85916851, -0.96706431, -0.84378798])

In [15]:
randint(1, 7, 12)

array([6, 1, 5, 6, 5, 5, 3, 3, 6, 3, 1, 2])

In [16]:
print(a.size)
print(a.sum())
print(a.mean())
print(a.var())
print(a.std())

6
21
3.5
2.91666666667
1.70782512766


In [17]:
round(2**0.5,3)

1.414

In [18]:
a = arange(-10,11)
less_than_five = (abs(a) < 5)
a[less_than_five]

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [19]:
a[(abs(a) < 5)]

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [20]:
b = [2, 4, 5]
a[b]

array([-8, -6, -5])

In [21]:
from random import choice
choice(['Hitler','Stalin','Jaruzelski'])

'Jaruzelski'

In [22]:
M = arange(100, dtype=int).reshape(10,10)
M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
M[2:9:2,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [24]:
M[2:9:2,5::-1]

array([[25, 24, 23, 22, 21, 20],
       [45, 44, 43, 42, 41, 40],
       [65, 64, 63, 62, 61, 60],
       [85, 84, 83, 82, 81, 80]])

In [25]:
row_index = (M[:,0]>=20) & (M[:,0]<=80)
col_index = M[0,:]>=5
M[row_index,:][:,col_index]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89]])

In [26]:
row_index = [1,1,2,7]
col_index = [0,2,4,8]
M[row_index,col_index]

array([10, 12, 24, 78])

In [27]:
M[row_index,:][:,col_index]

array([[10, 12, 14, 18],
       [10, 12, 14, 18],
       [20, 22, 24, 28],
       [70, 72, 74, 78]])